routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/',[FrontendController::class, 'index'])->name('frontend.index');

require __DIR__.'/auth.php';


Route::middleware('auth')->group(function(){

    Route::resource('products', ProductController::class);

    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class FrontendController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

            $products = Product::all();
            return view('frontend.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(15);
        return view('backend.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $requestData = [

            'name' => $request->name,
            'category_name' => $request->name,
            'brand_name' => $request->name,
            'description' => $request->description,
            'image' => $this->uploadImage($request->file('image'))
        ];

        $product = Product::create($requestData);

        // $product->colors()->attach($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('backend.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('backend.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $requestData = [
            'name' => $request->name,
            'category_name' => $request->category_name,
            'brand_name' => $request->brand_name,
            'description' => $request->description,
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }

        $product->update($requestData);
        // $product->colors()->sync($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->forceDelete();

        return redirect()
            ->route('products.index')
            ->withMessage('Successfully deleted');
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        // $image->move(storage_path('/app/public/products'), $fileName);

        Image::make($image)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/products/' . $fileName);

        return $fileName;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/backend/products/create.blade.php
<x-backend.master>
    <x-slot:title>
        {{ __('Product Create') }}
        </x-slot>
        <main class="main" id="main">

            <x-forms.message />

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">{{ __('Products') }}</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">
                            <span data-feather="list"></span>
                            {{ __('List') }}
                        </button>
                    </a>
                </div>
            </div>

            <x-forms.errors />

            <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                @csrf


                <x-forms.input type="text" name="name" placeholder="Enter Product Name" required
                    label="Product Name" />
                <x-forms.input type="text" name="category_name" placeholder="Enter Category Name" required
                    label="Category Name" />
                <x-forms.input type="text" name="brand_name" placeholder="Enter Brand Name" required
                    label="Brand Name" />
                    <x-forms.textarea name="description" label="Description" />
                <x-forms.input type="file" name="image" label='Picture' />

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </main>
</x-backend.master>

resources/views/backend/products/edit.blade.php
<x-backend.master>
    <x-slot:title>
        Product Create
        </x-slot>
        <main class="main" id="main">
            <x-forms.message />

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">{{ __('Products') }}</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">
                            <span data-feather="list"></span>
                            {{ __('List') }}
                        </button>
                    </a>
                </div>
            </div>

            <x-forms.errors />

            <form action="{{ route('products.update', $product->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')


                <x-forms.input type="text" name="name" :value="old('name', $product->name)" placeholder="Enter Name" required
                    label="Products name" />
                <x-forms.input type="text" name="category_name" :value="old('category_name', $product->category_name)" placeholder="Enter Category Name" required
                    label="Category name" />
                <x-forms.input type="text" name="brand_name" :value="old('brand_name', $product->brand_name)" placeholder="Enter Brand Name" required
                    label="Products name" />

                <x-forms.textarea name="description" label="Description" :value="old('description', $product->description)" />
                <x-forms.input type="file" name="image" label='Picture' />

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </main>
</x-backend.master>

resources/views/backend/products/index.blade.php
<x-backend.master>
    <x-slot:title>
        Product List
        </x-slot>

        <main class="main" id="main">
            <x-forms.message />

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Products</h1>

                <a href="{{ route('products.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Product Name</th>
                        <th width="180">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $product->name }}</td>
                            <td>
                                <a class="btn btn-sm btn-info"
                                    href="{{ route('products.show', $product->id) }}">Show</a>
                                <a class="btn btn-sm btn-warning"
                                    href="{{ route('products.edit', $product->id) }}">Edit</a>
                                <form action="{{ route('products.destroy', $product->id) }}" method="post"
                                    style="display:inline">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-danger"
                                        onclick="return confirm('Are you sure want to delete')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $products->links() }}

        </main>
</x-backend.master>

resources/views/backend/products/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->title }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/backend/products/show.blade.php
<x-backend.master>
    <x-slot:title>
        Product Details
        </x-slot>
        <main class="main" id="main">
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Product</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">
                            <span data-feather="list"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>
            <h1>Product Name: {{ $product->name }}</h1>
            <h1>Category Name: {{ $product->category_name }}</h1>
            <h1>Brand Name: {{ $product->brand_name }}</h1>
            <p>Description:{{ $product->description }}</p>
            <img src="{{ asset('storage/products/' . $product->image) }}" />
        </main>
</x-backend.master>

resources/views/backend/products/trash.blade.php
<x-admin.master>
    <x-slot:title>
        {{ __('Category List') }}
        </x-slot>

        <x-forms.message />
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ __('Categories Trash') }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="list"></span>
                        {{ __('List') }}
                    </button>
                </a>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>{{ __('SL#') }}</th>
                    <th>{{ __('Title') }}</th>
                    <th>{{ __('Action') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $category->title }}</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="{{ route('categories.show', $category->id) }}">Show</a>
                            <a class="btn btn-sm btn-warning"
                                href="{{ route('categories.restore', $category->id) }}">Restore</a>
                            <form action="{{ route('categories.delete', $category->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-sm btn-danger"
                                    onclick="return confirm('Are you sure want to delete')"
                                    title="Permanent Delete">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
</x-admin.master>

resources/views/dashboard.blade.php
<x-backend.master>
    <x-slot:title>
        Dashboard
    </x-slot:title>

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Dashboard</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section dashboard">
            <div class="row">
                <div class="col-md-4">
                    <div class="card info-card sales-card">

                        <div class="card-body">
                            <h5 class="card-title">Item sold <span>| Today</span></h5>

                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-cart"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>145</h6>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card info-card sales-card">

                        <div class="card-body">
                            <h5 class="card-title">Item Sold <span>| This Month</span></h5>

                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-cart"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>455</h6>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card info-card sales-card">

                        <div class="card-body">
                            <h5 class="card-title">Item Sold <span>| This Year</span></h5>

                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-cart"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>850</h6>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <!-- Charts -->
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">
                            <h5 class="card-title">Item sold by Category <span>/This Month</span></h5>
                            <!-- Bar Chart -->
                            <canvas id="barChart" style="max-height: 400px;"></canvas>
                            <script>
                                let categories = ['Fruits', 'Vegetables', 'Drinks', 'Ingridients'];
                                let categoryData = [267, 140, 243, 121];
                                document.addEventListener("DOMContentLoaded", () => {
                                    new Chart(document.querySelector('#barChart'), {
                                        type: 'bar',
                                        data: {
                                            labels: categories,
                                            datasets: [{
                                                label: "Category sales",
                                                data: categoryData,
                                                backgroundColor: [
                                                    'rgba(255, 99, 132, 0.2)',
                                                    'rgba(255, 159, 64, 0.2)',
                                                    'rgba(255, 205, 86, 0.2)',
                                                    'rgba(75, 192, 192, 0.2)',
                                                    'rgba(54, 162, 235, 0.2)',
                                                    'rgba(153, 102, 255, 0.2)',
                                                    'rgba(201, 203, 207, 0.2)'
                                                ],
                                                borderColor: [
                                                    'rgb(255, 99, 132)',
                                                    'rgb(255, 159, 64)',
                                                    'rgb(255, 205, 86)',
                                                    'rgb(75, 192, 192)',
                                                    'rgb(54, 162, 235)',
                                                    'rgb(153, 102, 255)',
                                                    'rgb(201, 203, 207)'
                                                ],
                                                borderWidth: 1
                                            }]
                                        },
                                        options: {
                                            responsive: true,
                                            scales: {
                                                y: {
                                                    beginAtZero: true
                                                }
                                            }
                                        }
                                    });
                                });
                            </script>
                            <!-- End Bar CHart -->
                        </div>

                    </div>
                </div>
                <!-- End Charts -->

                <!-- Top Selling -->
                <div class="col-12">
                    <div class="card top-selling overflow-auto">

                        <div class="card-body pb-0">
                            <h5 class="card-title">Top Sales <span>| Today</span></h5>

                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th scope="col">Preview</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Price (৳)</th>
                                        <th scope="col">Sold</th>
                                        <th scope="col">Revenue (৳)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">
                                            <a href="#">
                                                <img src="../Picture/Fruites/banana-chompa-ready-to-eat-12-pcs.webp"
                                                    alt="">
                                            </a>
                                        </th>
                                        <td>Chompa Kola</td>
                                        <td>70</td>
                                        <td class="fw-bold">124 Dozen</td>
                                        <td>5,828</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">
                                            <a href="#"><img src="../Picture/Fruites/gala-apple-50-gm-1-kg.webp"
                                                    alt=""></a>
                                        </th>
                                        <td>Gala Apple</td>
                                        <td>290</td>
                                        <td class="fw-bold">20 Kg</td>
                                        <td>5,500</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">
                                            <a href="#"><img
                                                    src="../Picture/Fruites/kacha-aam-green-mango-50-gm-1-kg.webp"
                                                    alt=""></a>
                                        </th>
                                        <td>Kacha Amm</td>
                                        <td>50</td>
                                        <td class="fw-bold">80 Kg</td>
                                        <td>4,000</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                <!-- End Top Selling -->

                <!-- Recent Sales -->
                <div class="col-12">
                    <div class="card recent-sales overflow-auto">

                        <div class="card-body">
                            <h5 class="card-title">Recent Sales <span>| Today</span></h5>

                            <table class="table table-borderless datatable">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Customer</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Price (৳)</th>
                                        <th scope="col">Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row"><a href="#">20</a></th>
                                        <td>Lorem Ipsum</td>
                                        <td>Chompa Kola</td>
                                        <td>70</td>
                                        <td>1 Dozen</td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">23</a></th>
                                        <td>Dolor Sit</td>
                                        <td>Kacha Amm</td>
                                        <td>50</td>
                                        <td>5 Kg</td>
                                    </tr>
                                    <tr>
                                        <th scope="row"><a href="#">9</a></th>
                                        <td>Amet Consectetur</td>
                                        <td>Gala Apple</td>
                                        <td>290</td>
                                        <td>5 Kg</td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
                <!-- End Recent Sales -->

            </div>
        </section>
    </main>

</x-backend.master>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>